name: GiSTX
description: Cross-platform Questionnaire software
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0
  uuid: ^4.5.1
  path: ^1.9.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3
  # for desktop (Windows) â€“ sqflite on FFI
  sqflite_common_ffi: ^2.3.2
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
  csv: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/surveys/fake_household_survey/
    - assets/surveys/fake_clinical_trial/
    - assets/branding/gistx.png
    - assets/database/

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/branding/gistx.png"
  min_sdk_android: 21
  windows:
    generate: true
    icon_size: 256
    icon_file: "assets/branding/gistx.png"